import type { Axis, AxisKey, InvestorType, Question } from "./types";

export const axes: Record<AxisKey, Axis> = {
  risk: {
    label: "リスク",
    description: "値動きの大きさを、どのくらい自然に受け止められるか。",
    left: "安定重視",
    right: "成長重視",
    negativeCode: "S",
    positiveCode: "R",
  },
  horizon: {
    label: "時間軸",
    description: "成果を確認したいペースが、短い周期か長い時間か。",
    left: "短期重視",
    right: "長期重視",
    negativeCode: "T",
    positiveCode: "L",
  },
  involvement: {
    label: "関与度",
    description: "仕組みに任せたいか、自分で情報を追って判断したいか。",
    left: "おまかせ運用",
    right: "自分で選ぶ",
    negativeCode: "P",
    positiveCode: "A",
  },
  reward: {
    label: "収益源",
    description: "入金の安心感と値上がりの期待、どちらに心が動きやすいか。",
    left: "インカム重視",
    right: "値上がり重視",
    negativeCode: "I",
    positiveCode: "G",
  },
};

export const questions: Question[] = [
  {
    axis: "risk",
    text: "持っている資産が10%下がったら、どう感じそう？",
    choices: [
      { text: "理由を確認して、納得できれば持ち続ける", value: 1 },
      { text: "不安が強くなるので、早めに守りを固めたい", value: -1 },
    ],
  },
  {
    axis: "horizon",
    text: "投資の手応えは、どのくらいのペースで見たい？",
    choices: [
      { text: "数年かけて育っていれば十分", value: 1 },
      { text: "数週間から数か月で変化を感じたい", value: -1 },
    ],
  },
  {
    axis: "involvement",
    text: "投資先を選ぶ作業は、どちらに近い？",
    choices: [
      { text: "会社やニュースを調べるのも楽しめそう", value: 1 },
      { text: "できるだけ仕組みに任せて、迷う回数を減らしたい", value: -1 },
    ],
  },
  {
    axis: "reward",
    text: "投資でうれしいと感じるのは、どちらに近い？",
    choices: [
      { text: "将来大きく伸びる可能性を持っていること", value: 1 },
      { text: "定期的に入ってくるお金の安心感があること", value: -1 },
    ],
  },
  {
    axis: "risk",
    text: "値動きが大きい投資先への印象は？",
    choices: [
      { text: "一部なら、成長のチャンスとして面白い", value: 1 },
      { text: "大きく下がる可能性が気になって慎重になる", value: -1 },
    ],
  },
  {
    axis: "horizon",
    text: "気になる投資先を見つけたら、どう動きたい？",
    choices: [
      { text: "チャンスを逃さないうちに小さく試したい", value: -1 },
      { text: "長く持てる理由があるかを先に確かめたい", value: 1 },
    ],
  },
  {
    axis: "involvement",
    text: "月に一度、投資を見直すならどこまでやりたい？",
    choices: [
      { text: "積立額と全体のバランスを見て終わりにしたい", value: -1 },
      { text: "気になる投資先やニュースまで見ておきたい", value: 1 },
    ],
  },
  {
    axis: "reward",
    text: "魅力を感じる会社はどちら？",
    choices: [
      { text: "利益を使って、さらに成長しようとしている会社", value: 1 },
      { text: "安定した利益を、配当などで返してくれる会社", value: -1 },
    ],
  },
  {
    axis: "risk",
    text: "相場全体が大きく下がった日に、取りやすい行動は？",
    choices: [
      { text: "安くなった投資先がないか探してみる", value: 1 },
      { text: "まず手元資金や守りの比率を確認する", value: -1 },
    ],
  },
  {
    axis: "horizon",
    text: "理想の増え方はどちらに近い？",
    choices: [
      { text: "小さく動きながら、こまめに手応えを得る", value: -1 },
      { text: "時間を味方につけて、じっくり増やす", value: 1 },
    ],
  },
  {
    axis: "involvement",
    text: "週末に投資のことを考えるなら、どれくらいが自然？",
    choices: [
      { text: "15分くらいで十分。生活の時間を優先したい", value: -1 },
      { text: "1時間以上でも、調べ始めると集中できそう", value: 1 },
    ],
  },
  {
    axis: "reward",
    text: "資産一覧を見てうれしいのはどちら？",
    choices: [
      { text: "配当や分配金の予定が並んでいる", value: -1 },
      { text: "将来伸びそうな投資先が育っている", value: 1 },
    ],
  },
  {
    axis: "risk",
    text: "大きく上がった投資先の比率が増えたら？",
    choices: [
      { text: "まだ伸びる理由があるなら、そのまま持ちたい", value: 1 },
      { text: "増えすぎた分を調整して、バランスを整えたい", value: -1 },
    ],
  },
  {
    axis: "horizon",
    text: "投資先を選ぶとき、重視したい情報は？",
    choices: [
      { text: "数年先までの成長余地や事業の強さ", value: 1 },
      { text: "直近のニュース、値動き、タイミング", value: -1 },
    ],
  },
  {
    axis: "involvement",
    text: "投資先に予想外のニュースが出たら？",
    choices: [
      { text: "内容を読んで、自分で判断を見直したい", value: 1 },
      { text: "あらかじめ決めたルールの範囲で対応したい", value: -1 },
    ],
  },
  {
    axis: "reward",
    text: "投資の成果として分かりやすいのは？",
    choices: [
      { text: "持っている資産の評価額が大きく伸びたこと", value: 1 },
      { text: "年間の配当や分配金が積み上がったこと", value: -1 },
    ],
  },
  {
    axis: "risk",
    text: "投資に前向きになりやすいのは、どんなとき？",
    choices: [
      { text: "納得できるチャンスが見えてきたとき", value: 1 },
      { text: "相場に関係なく、無理のないペースを守れるとき", value: -1 },
    ],
  },
  {
    axis: "horizon",
    text: "投資で避けたい失敗はどちら？",
    choices: [
      { text: "目先の不安で、長く持ちたいものを手放すこと", value: 1 },
      { text: "変化に気づいていたのに、動くのが遅れること", value: -1 },
    ],
  },
  {
    axis: "involvement",
    text: "理想の投資スタイルはどちらに近い？",
    choices: [
      { text: "自分で候補を選び、理由を考えながら進めたい", value: 1 },
      { text: "投資先や配分は、できるだけ仕組みに任せたい", value: -1 },
    ],
  },
  {
    axis: "reward",
    text: "より惹かれる投資先はどちら？",
    choices: [
      { text: "今は小さくても、これから大きく伸びそうな投資先", value: 1 },
      { text: "大きな成長より、安定した入金が期待できる投資先", value: -1 },
    ],
  },
];

export const investorTypes: Record<string, InvestorType> = {
  SLPI: {
    role: "配当の守護者",
    mark: "防",
    motif: "shield",
    line: "毎月の安心感こそ、いちばん強いメンタル資産。",
    shareLine: "毎年の配当が育つと、それだけで安心できる。",
    summary: "低リスク、長期、おまかせ運用、インカム重視。安定した入金感を積み上げる、堅実な資産管理タイプです。",
    preferredMethods: ["高配当株", "高配当ETF", "債券ファンド"],
    strength: "焦らず続ける力があり、生活防衛と資産形成のバランスを崩しにくいところ。",
    watchout: "守りが強いぶん、成長機会を見送る場面が増えやすいところ。",
    colors: ["#197c75", "#d49a2f"],
  },
  SLPG: {
    role: "複利の庭師",
    mark: "複",
    motif: "growth",
    line: "今日の退屈は、未来の自由に変わる。",
    shareLine: "今日も淡々と積み立てる。それがいちばん強い。",
    summary: "低リスク、長期、おまかせ運用、成長重視。インデックスや分散投資で、時間の力を味方につけます。",
    preferredMethods: ["全世界株式インデックス", "S&P500インデックス", "積立投資"],
    strength: "派手さに流されず、仕組みと時間を味方にできるところ。",
    watchout: "順調なときほど点検が薄くなり、配分が古くなること。",
    colors: ["#2f5d8c", "#197c75"],
  },
  SLAI: {
    role: "利回りの職人",
    mark: "配",
    motif: "dividend",
    line: "良い会社から、良いリズムで受け取る。",
    shareLine: "利回りだけじゃなく、払い続ける力まで見たい。",
    summary: "低リスク、長期、自分で選ぶ、インカム重視。財務の安定性や還元方針を丁寧に見ます。",
    preferredMethods: ["高配当株", "連続増配株", "REIT"],
    strength: "数字の裏側まで見て、無理のないキャッシュフローを組めるところ。",
    watchout: "配当の心地よさに寄りすぎて、事業の成長鈍化を許しがちなところ。",
    colors: ["#d49a2f", "#172026"],
  },
  SLAG: {
    role: "良株の庭師",
    mark: "品",
    motif: "quality",
    line: "強い事業は、急がせずに育てたい。",
    shareLine: "良い会社なら、時間をかけて付き合いたい。",
    summary: "低リスク、長期、自分で選ぶ、成長重視。強い事業を見つけ、じっくり育てるのが得意です。",
    preferredMethods: ["優良株投資", "成長株投資", "長期個別株投資"],
    strength: "事業の質を見抜き、長く付き合う銘柄を選ぶ観察力。",
    watchout: "好きな企業に甘くなり、見直す理由を後回しにしやすいところ。",
    colors: ["#197c75", "#c64b45"],
  },
  STPI: {
    role: "守りの操縦士",
    mark: "守",
    motif: "shield",
    line: "増やす前に、まず減らさない設計をする。",
    shareLine: "まず減らさない。動くのは守りを固めてから。",
    summary: "低リスク、短期、おまかせ運用、インカム重視。大きな変化より、守りの基準と流動性を優先します。",
    preferredMethods: ["債券ファンド", "バランスファンド", "預金・待機資金"],
    strength: "判断基準を守り、次の機会に向けて余力を残せるところ。",
    watchout: "守りの確認が早くなり、育つ途中の手応えを見切りやすいところ。",
    colors: ["#637075", "#d49a2f"],
  },
  STPG: {
    role: "規律の相場剣士",
    mark: "律",
    motif: "rule",
    line: "感情はチャートに書き込まない。",
    shareLine: "上がりそう、よりもルール通りかを先に見る。",
    summary: "低リスク、短期、おまかせ運用、成長重視。感情を抑えたルール運用で、機会を絞って見ます。",
    preferredMethods: ["インデックスETF", "バランスファンド", "積立投資"],
    strength: "ルール化によって迷いを減らし、同じ型で検証できるところ。",
    watchout: "相場環境が変わっても、古いルールを使い続けやすいところ。",
    colors: ["#2f5d8c", "#d49a2f"],
  },
  STAI: {
    role: "市場の観測者",
    mark: "観",
    motif: "observer",
    line: "入るより先に、出方を決めておく。",
    shareLine: "入る前に、まず理由と数字をじっくり見たい。",
    summary: "低リスク、短期、自分で選ぶ、インカム重視。状況をよく見て、小さく検証しながら判断します。",
    preferredMethods: ["高配当株", "REIT", "債券ファンド"],
    strength: "観察と検証を重ね、危ない局面で深追いしにくいところ。",
    watchout: "考える時間が長くなり、決断のタイミングを逃しやすいところ。",
    colors: ["#637075", "#197c75"],
  },
  STAG: {
    role: "機会の狩人",
    mark: "選",
    motif: "hunter",
    line: "動くなら、理由がそろった時だけ。",
    shareLine: "チャンスは待つ。条件がそろった時だけ狙う。",
    summary: "低リスク、短期、自分で選ぶ、成長重視。守りを固めつつ、確度の高い局面を探します。",
    preferredMethods: ["国内株", "セクターETF", "成長株投資"],
    strength: "リスクを絞りながら、伸びる局面を見つける嗅覚。",
    watchout: "完璧な条件を待ちすぎて、実行数が少なくなるところ。",
    colors: ["#c64b45", "#2f5d8c"],
  },
  RLPI: {
    role: "配分の航海士",
    mark: "配",
    motif: "allocation",
    line: "揺れはある。だから配分で受け止める。",
    shareLine: "攻める資産も、配分でなら落ち着いて持てる。",
    summary: "高リスク、長期、おまかせ運用、インカム重視。大きな配分方針を決め、値動きも受け止めます。",
    preferredMethods: ["バランスファンド", "高配当ETF", "インデックス投資"],
    strength: "大きな視点でポートフォリオを設計し、ぶれずに持てるところ。",
    watchout: "一度決めた配分への信頼が強く、環境変化の確認が遅れること。",
    colors: ["#c64b45", "#d49a2f"],
  },
  RLPG: {
    role: "世界複利の旅人",
    mark: "世",
    motif: "global",
    line: "世界の成長に、長く乗っていく。",
    shareLine: "世界まるごとの成長に、長く乗っていたい。",
    summary: "高リスク、長期、おまかせ運用、成長重視。世界の成長テーマを広く取り込み、長期で待てます。",
    preferredMethods: ["全世界株式インデックス", "米国株インデックス", "積立投資"],
    strength: "広い視野で成長領域を取り込み、短期の揺れに耐えられるところ。",
    watchout: "テーマを広げすぎると、自分が何に期待しているか曖昧になるところ。",
    colors: ["#2f5d8c", "#c64b45"],
  },
  RLAI: {
    role: "利回りの錬金術師",
    mark: "利",
    motif: "yield",
    line: "高い利回りには、見ておきたい理由がある。",
    shareLine: "高い利回りほど、その理由まで確かめたい。",
    summary: "高リスク、長期、自分で選ぶ、インカム重視。利回りの裏側にある事業リスクまで読み込みます。",
    preferredMethods: ["高配当株", "REIT", "債券ファンド"],
    strength: "収益性、財務、還元方針を立体的に見て判断できるところ。",
    watchout: "分析に自信があるぶん、リスクの大きい利回りにも納得感を持ちやすいところ。",
    colors: ["#d49a2f", "#c64b45"],
  },
  RLAG: {
    role: "未来航路の探求者",
    mark: "未",
    motif: "vision",
    line: "未来が変わるなら、今から席を取っておく。",
    shareLine: "まだ早いと言われる場所に、少し先回りしたい。",
    summary: "高リスク、長期、自分で選ぶ、成長重視。未来の市場や企業の可能性に強く惹かれるタイプです。",
    preferredMethods: ["成長株投資", "テーマ投資", "米国株"],
    strength: "大きな変化を早く見つけ、時間を味方に大胆に保有できるところ。",
    watchout: "物語が魅力的すぎると、数字の現実を見落としやすいところ。",
    colors: ["#c64b45", "#197c75"],
  },
  RTPI: {
    role: "資金回転の軽業師",
    mark: "流",
    motif: "cashflow",
    line: "回転させるなら、ルールも資金も軽くしておく。",
    shareLine: "資金は寝かせすぎず、次の入金先へ回したい。",
    summary: "高リスク、短期、おまかせ運用、インカム重視。収益機会をルール化し、素早い見直しを好みます。",
    preferredMethods: ["高配当ETF", "REIT", "短期債券ファンド"],
    strength: "資金効率を意識し、短期の機会を淡々と処理できるところ。",
    watchout: "回転の速さが目的化し、手数やコストが増えやすいところ。",
    colors: ["#172026", "#d49a2f"],
  },
  RTPG: {
    role: "波乗りの機工士",
    mark: "波",
    motif: "system",
    line: "波を読むより、波に乗る条件を決める。",
    shareLine: "流れが来ているなら、ルールを決めて乗りたい。",
    summary: "高リスク、短期、おまかせ運用、成長重視。トレンドやモメンタムを、規律ある仕組みで追います。",
    preferredMethods: ["インデックスETF", "セクターETF", "米国株"],
    strength: "勢いのある相場に対して、感情よりルールで動けるところ。",
    watchout: "逆回転が始まったとき、連続して外れる前提を忘れやすいところ。",
    colors: ["#172026", "#2f5d8c"],
  },
  RTAI: {
    role: "材料読みの軍師",
    mark: "策",
    motif: "event",
    line: "材料、需給、時間。そろったら動く。",
    shareLine: "ニュースの意味を読んで、動くタイミングを探す。",
    summary: "高リスク、短期、自分で選ぶ、インカム重視。材料、需給、タイミングをつなげて判断します。",
    preferredMethods: ["国内株", "米国株", "高配当株"],
    strength: "複数の情報をつなげ、短い機会の変化を見抜けるところ。",
    watchout: "情報量が多いほど、確信と錯覚の境目が近くなるところ。",
    colors: ["#197c75", "#172026"],
  },
  RTAG: {
    role: "成長波の切り込み役",
    mark: "攻",
    motif: "trend",
    line: "伸びるなら速く、違うならすぐ切る。",
    shareLine: "伸びる物語が見えたら、早めに乗ってみたい。",
    summary: "高リスク、短期、自分で選ぶ、成長重視。値動きと成長期待の両方に反応しやすいタイプです。",
    preferredMethods: ["成長株投資", "テーマ投資", "米国株"],
    strength: "強いテーマや値動きに素早く反応し、変化を見逃しにくいところ。",
    watchout: "熱量が高いぶん、投資額の感覚が大きくなりやすいところ。",
    colors: ["#c64b45", "#172026"],
  },
};

export const adviceByAxis: Record<AxisKey, { positive: string; negative: string }> = {
  risk: {
    positive: "値動きの大きい資産に惹かれやすいので、自分が落ち着いて見られる上限比率を決めておくと安心です。",
    negative: "安定を重視しやすいので、機会を見送る理由が習慣になっていないかを時々振り返ると視野が広がります。",
  },
  horizon: {
    positive: "長期で考えやすいので、保有を続ける前提と見直す条件を同じ紙に置いておくと判断を振り返りやすくなります。",
    negative: "短期の手応えを重視しやすいので、判断理由と結果を残すと自分の得意な局面が見えやすくなります。",
  },
  involvement: {
    positive: "自分で調べるほど確信が強くなりやすいので、反対材料を見る時間も予定に入れるとバランスを取りやすくなります。",
    negative: "仕組みに任せるのが得意なので、年1回だけ配分や前提を見直す日を決めておくと放置に気づきやすくなります。",
  },
  reward: {
    positive: "値上がりの期待に目が向きやすいので、追いかける指標を少数に絞ると期待と現実を比べやすくなります。",
    negative: "利回りや入金の安心感を重視しやすいので、その安心がどんな前提で成り立つかを一緒に見ると納得感が増します。",
  },
};
